#!/usr/bin/env python3
"""Capability-gating primitives for agents, skills, and plugins.

Session capabilities come from the client-advertised
``X-Mewbo-Capabilities`` header (persisted on the session's context
event as ``client_capabilities``). Entries — agents, skills, or plugin
contributions — can declare ``requires_capabilities`` to stay hidden
from any session that hasn't advertised the matching capability.

Both functions are pure: no I/O, no state. They operate on tuples so
the results are hashable and safely cachable.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable
from dataclasses import replace
from typing import Literal, Protocol, TypeVar

from mewbo_core.common import get_logger

logging = get_logger(name="core.capabilities")


class _HasRequiresCapabilities(Protocol):
    requires_capabilities: tuple[str, ...]


_T = TypeVar("_T", bound=_HasRequiresCapabilities)

# The FIRST-PARTY capability vocabulary — a closed ``Literal`` plus a runtime
# frozenset, the same shape ``AgentStatus`` uses (``agents/hypervisor.py``) and
# for the same reason: it is a contract shared across three languages, so it is
# hand-mirrored into each client behind a tripwire test
# (``tests/test_capability_registry.py``) rather than generated by a build step.
#
# Deliberately a ``Literal`` rather than an enum. Every consumer wants the bare
# string — a comma-joined header, a JSON manifest's ``requires-capabilities``, a
# set-membership test — so a ``Literal`` gives mypy a closed set at annotated
# boundaries while leaving all of those call sites working verbatim. ``StrEnum``
# would fit but needs 3.11 (this package declares ``>=3.10``), and the 3.10-safe
# ``(str, Enum)`` spelling renders as ``Capability.ASK_USER`` inside an f-string,
# which would corrupt a header with nothing raised.
#
# **This is not an exhaustive list of every capability that can exist.** A
# third-party plugin may ship its own id and MUST keep working: the operator
# facing list is COMPUTED from installed manifests
# (``mewbo_api/system_instructions/value_sources.py:_capabilities``), never from
# this registry. What this registry closes is the set the FIRST-PARTY clients
# advertise and the first-party plugins require — which is exactly the set that
# was drifting across four surfaces.
Capability = Literal[
    "apps",
    "ask_user",
    "device_control",
    "generative_ui",
    "scg",
    "speech_capture",
    "speech_playback",
    "stlite",
    "wiki",
]

APPS_CAPABILITY: Capability = "apps"
"""The client renders the Mewbo Apps surface and can host a served app."""

ASK_USER_CAPABILITY: Capability = "ask_user"
"""The client can render a question card and POST the answer back.

Gates the block-until-answered ``ask_user_question`` tool. A headless drive
(triggers, wiki, search, channels) never advertises it, so the tool does not
exist for those runs and nothing blocks waiting for a human who is not there.
"""

DEVICE_CONTROL_CAPABILITY: Capability = "device_control"
"""The client's claim that it can OBSERVE and DRIVE the device's screen.

Named here rather than in the api because two independent surfaces must agree
on the literal: the skill gate (a plugin's ``requires-capabilities``) and the
event bus's executor flag, which decides whether a device-tool dispatch has
anyone to deliver to. They were separate strings once and diverging them is
exactly how a session ends up holding the playbook for tools it cannot call.
"""

GENERATIVE_UI_CAPABILITY: Capability = "generative_ui"
"""The client has the allowlist renderer for a model-authored UI tree.

Gates the ``present_ui`` SessionTool. Advertising it and rendering the result
are ONE decision: a surface that advertised without rendering would let a run
spend a step producing a panel nobody can read.
"""

SCG_CAPABILITY: Capability = "scg"
"""The session is scoped to the Source Capability Graph substrate."""

SPEECH_CAPTURE_CAPABILITY: Capability = "speech_capture"
"""The client can RECORD audio from a microphone and upload it.

Deliberately separate from :data:`SPEECH_PLAYBACK_CAPABILITY`: playing audio and
capturing it are different permissions backed by different hardware, and a
surface routinely has one without the other. A browser tab with no mic grant, or
one served over plain HTTP where ``getUserMedia`` is unavailable, can still play
synthesized audio — so collapsing the two into one ``speech`` id would either
silently offer dictation that cannot start or withhold playback that works.
"""

SPEECH_PLAYBACK_CAPABILITY: Capability = "speech_playback"
"""The client can PLAY synthesized audio it is handed.

See :data:`SPEECH_CAPTURE_CAPABILITY` for why the two halves are separate ids.
"""

STLITE_CAPABILITY: Capability = "stlite"
"""The client can mount a Streamlit-lite widget (the ``widget_ready`` card)."""

WIKI_CAPABILITY: Capability = "wiki"
"""The session is scoped to the MewboWiki substrate."""

ALL_CAPABILITIES: frozenset[Capability] = frozenset(
    {
        APPS_CAPABILITY,
        ASK_USER_CAPABILITY,
        DEVICE_CONTROL_CAPABILITY,
        GENERATIVE_UI_CAPABILITY,
        SCG_CAPABILITY,
        SPEECH_CAPTURE_CAPABILITY,
        SPEECH_PLAYBACK_CAPABILITY,
        STLITE_CAPABILITY,
        WIKI_CAPABILITY,
    }
)
"""Every first-party capability id. The tripwire test pins the client mirrors to it."""

# The wire separator for ``X-Mewbo-Capabilities``. Spelled once so the parse and
# the serialize halves cannot disagree about it.
CAPABILITY_HEADER = "X-Mewbo-Capabilities"
_HEADER_SEPARATOR = ","

# A runtime predicate that, given the capabilities a session ALREADY advertised,
# returns extra capability ids to grant it (or ``()``). The signature is the
# advertised tuple so a provider can no-op when its capability is already present.
SessionCapabilityProvider = Callable[[tuple[str, ...]], Iterable[str]]

# Down-only push seam (mirrors ``plugins.register_builtin_root`` /
# ``scg.map_phase.MapPhaseSink``): an OPTIONAL capability library above core in
# the DAG registers a provider so a capability can be granted by a RUNTIME
# predicate (e.g. ``scg`` once the SCG is enabled AND a source is mapped),
# without core ever importing up to evaluate that predicate. Empty by default —
# a lean install grants nothing extra.
_CAPABILITY_PROVIDERS: list[SessionCapabilityProvider] = []


def register_session_capability_provider(provider: SessionCapabilityProvider) -> None:
    """Register a runtime provider that may grant extra session capabilities.

    Idempotent on identity and down-only (a library above core pushes here on
    import). Called by :func:`augment_session_capabilities` per session-init, so
    a freshly-mapped graph flips a live process without a restart.
    """
    if provider not in _CAPABILITY_PROVIDERS:
        _CAPABILITY_PROVIDERS.append(provider)


def reset_session_capability_providers() -> None:
    """Drop all registered providers (test isolation seam)."""
    _CAPABILITY_PROVIDERS.clear()


def augment_session_capabilities(advertised: tuple[str, ...]) -> tuple[str, ...]:
    """Union *advertised* with every registered provider's runtime grant.

    Each provider is best-effort: a raising provider is logged and skipped so a
    flaky predicate (an unreachable store) never breaks session init. Returns a
    sorted, deduped tuple so the result stays hashable + cache-stable like
    :func:`parse_capabilities`. A no-provider install returns *advertised*
    unchanged.
    """
    if not _CAPABILITY_PROVIDERS:
        return advertised
    granted: set[str] = set(advertised)
    for provider in _CAPABILITY_PROVIDERS:
        try:
            granted.update(str(c).strip() for c in provider(advertised) if str(c).strip())
        except Exception as exc:  # noqa: BLE001 — a predicate must never break init
            logging.warning(
                "session capability provider failed: {}: {}", type(exc).__name__, exc
            )
    return tuple(sorted(granted))


def parse_capabilities(raw: object) -> tuple[str, ...]:
    """Normalise frontmatter/manifest input into a deterministic tuple.

    Accepts ``None`` (→ ``()``), a single string (``"stlite"`` → ``("stlite",)``),
    or a list of strings (``["b", "a"]`` → ``("a", "b")`` — sorted, deduped,
    trimmed). Any other shape returns ``()``.
    """
    if raw is None:
        return ()
    if isinstance(raw, str):
        value = raw.strip()
        return (value,) if value else ()
    if isinstance(raw, list):
        items = sorted({str(v).strip() for v in raw if v and str(v).strip()})
        return tuple(items)
    return ()


def parse_capability_header(raw: object) -> tuple[str, ...]:
    """Parse an ``X-Mewbo-Capabilities`` header value into a normalised tuple.

    The ONE definition of the wire format's read half (:func:`serialize_capabilities`
    is the write half). Splits on commas, strips, drops empties, dedupes and
    sorts — so the same advertisement always produces the same tuple regardless
    of the order or spacing a client sent it in.

    **An unrecognised id is KEPT, and logged at debug once per parse.** Two
    reasons it must not be dropped, and neither is stylistic:

    * A third-party plugin legitimately ships its own capability id. Nothing in
      this process knows that id — the operator-facing list is computed from
      INSTALLED MANIFESTS, not from :data:`ALL_CAPABILITIES` — so filtering to
      the first-party registry would silently disable every third-party gate.
    * A newer client talking to an older server must degrade, not fail. Refusing
      the request would turn a rolling deploy into an outage.

    So the registry is a MIRROR-CHECKING device (see the tripwire test), never a
    wire validator. The log line exists so an id that is merely misspelled has
    somewhere to show up; it is ``debug`` rather than ``warning`` because a
    third-party id is expected traffic, not a fault.

    Cost: ``O(1)`` in stored data — it touches only the header string.
    """
    if not isinstance(raw, str):
        return ()
    parsed = sorted({part.strip() for part in raw.split(_HEADER_SEPARATOR) if part.strip()})
    unknown = [c for c in parsed if c not in ALL_CAPABILITIES]
    if unknown:
        logging.debug(
            "capability header carries {} id(s) outside the first-party registry: {} "
            "(kept — a third-party plugin or a newer client may own them)",
            len(unknown),
            ", ".join(unknown),
        )
    return tuple(parsed)


def serialize_capabilities(capabilities: Iterable[str]) -> str:
    """Render capabilities as an ``X-Mewbo-Capabilities`` header value.

    The write half of :func:`parse_capability_header`, and the one place the
    comma join lives on the python side — it was hand-spelled at three call
    sites before. Sorted and deduped so the header round-trips through the
    parser unchanged, which is what lets a test assert the two are inverses.

    Cost: ``O(1)`` in stored data.
    """
    return _HEADER_SEPARATOR.join(
        sorted({str(c).strip() for c in capabilities if str(c).strip()})
    )


def filter_by_capabilities(
    items: Iterable[_T], session_capabilities: Iterable[str]
) -> list[_T]:
    """Return items whose ``requires_capabilities`` is a subset of the session's.

    Items with empty ``requires_capabilities`` are always included — they
    require nothing. The comparison uses set semantics; ordering of
    ``session_capabilities`` does not matter.
    """
    session = set(session_capabilities)
    return [
        item
        for item in items
        if not item.requires_capabilities
        or set(item.requires_capabilities).issubset(session)
    ]


def overlay_capabilities(spec: _T, extra: Iterable[str]) -> _T:
    """Return a copy of *spec* with *extra* unioned into ``requires_capabilities``.

    Used when a plugin declares bundle-level ``requires-capabilities`` that
    must fan out over every contributed agent and skill. A no-op when
    *extra* is empty; otherwise produces a sorted, deduped tuple.
    """
    extra_tuple = tuple(extra)
    if not extra_tuple:
        return spec
    merged = tuple(sorted({*extra_tuple, *spec.requires_capabilities}))
    # All concrete call-sites pass frozen dataclasses (AgentDef, SkillSpec);
    # the protocol can't enforce dataclass-ness, so narrow here.
    return replace(spec, requires_capabilities=merged)  # type: ignore[type-var]


__all__ = [
    "ALL_CAPABILITIES",
    "APPS_CAPABILITY",
    "ASK_USER_CAPABILITY",
    "CAPABILITY_HEADER",
    "DEVICE_CONTROL_CAPABILITY",
    "GENERATIVE_UI_CAPABILITY",
    "SCG_CAPABILITY",
    "SPEECH_CAPTURE_CAPABILITY",
    "SPEECH_PLAYBACK_CAPABILITY",
    "STLITE_CAPABILITY",
    "WIKI_CAPABILITY",
    "Capability",
    "SessionCapabilityProvider",
    "augment_session_capabilities",
    "filter_by_capabilities",
    "overlay_capabilities",
    "parse_capabilities",
    "parse_capability_header",
    "register_session_capability_provider",
    "reset_session_capability_providers",
    "serialize_capabilities",
]
